version: '3.1'
services:
  vpn:
    restart: always
    image: koluch/ipsec-vpn-server
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    hostname: ipsec-vpn-server
    container_name: ipsec-vpn-server
    volumes:
      - /lib/modules:/lib/modules:ro
      - ./etc/ppp/chap-secrets:/etc/ppp/chap-secrets
      - ./etc/ipsec.d/passwd:/etc/ipsec.d/passwd
      - ./etc/ipsec.secrets:/etc/ipsec.secrets
